import Head from "next/head";
import Image from "next/image";
import Avatar from "../components/Avatar";
import { HiOutlineViewGrid, HiOutlineMicrophone } from "react-icons/hi";
import { AiOutlineSearch } from "react-icons/ai";
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/router";
export default function Home() {
  const searchRef = useRef(null);
  const route = useRouter();
  const Search = (e) => {
    e.preventDefault();
    const term = searchRef.current.value;
    if (!term) return;
    route.push(`/search?term=${term}`);
    console.log(term);
  };
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex justify-between p-3 w-full  text-gray-700">
        <div className="flex space-x-3">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        <div className="flex space-x-3">
          <p className="link mt-1">Gmail</p>
          <p className="link mt-1">Images</p>
          <HiOutlineViewGrid
            className="h-10 w-10 p-2 cursor-pointer rounded-full hover:bg-gray-100"
            onClick={() => alert("4")}
          />
          <Avatar url="https://picsum.photos/200/300" />
        </div>
      </header>
      <form className="flex flex-col items-center mt-44 flex-grow w-4/5 mx-auto">
        <Image
          src="https://www.google.co.uk/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          height={100}
          width={300}
        />
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md mx-auto px-5 py-3 rounded-full border border-gray-200 items-center sm:max-w-xl">
          <AiOutlineSearch />
          <input
            ref={searchRef}
            className="focus:outline-none flex-grow px-3"
          />
          <HiOutlineMicrophone />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 mt-8 justify-center sm:flex-row sm:space-x-4 sm:space-y-0">
          <button className="btn" onClick={Search}>
            Google Search
          </button>
          <button className="btn">Im feeling lucky</button>
        </div>
      </form>
      <Footer />
    </div>
  );
}
